# development profile

server:
  servlet:
    context-path: '/api'
  port: '8085'

spring:
  jpa:
    generate-ddl: false
  datasource:
    url: jdbc:postgresql://localhost:5433/rentacardb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password : rentacardbpsw

  config:
    activate:
      on-profile: prod

---

# production profile

server:
  servlet:
    context-path: '/api'
  port: '8080'

spring:
  jpa:
    generate-ddl: false
  datasource:
    url: jdbc:postgresql://localhost:5433/rentacardb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password : rentacardbpsw

  config:
    activate:
      on-profile: dev

---

# test profile

server:
  servlet:
    context-path: '/api'
  port: '8080'

spring:
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password : password
  h2:
    console:
      enabled: on
  config:
    activate:
      on-profile: test
  flyway:
    enabled: false