# development profile

server:
  servlet:
    context-path: '/api'
  port: '8085'

spring:
  jpa:
    generate-ddl: false
  datasource:
    url: jdbc:postgresql://localhost:5433/rentacardb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password : rentacardbpsw

  config:
    activate:
      on-profile: prod

---

# production profile

server:
  servlet:
    context-path: '/api'
  port: '8080'

spring:
  jpa:
    generate-ddl: false
  datasource:
    url: jdbc:postgresql://localhost:5433/rentacardb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password : rentacardbpsw

  config:
    activate:
      on-profile: dev